apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
  namespace: default
  labels:
    app: {{ .Values.appName }}-pub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}-pub
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-pub
    spec:
      containers:
      - name: publisher
        image: publishtest:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8000
        env:
        - name: RABBIT_USER
          value: user
        - name: RABBIT_PWD
          value: OqKZe6JVbG0DpbyU

