apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx 
  rules:
    - host: home.gateway
      http:
        paths:
          - path: /elo(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: ultra-elo-pub
                port:
                  number: 8000
          - path: /rabbit(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: rabbit-rabbitmq
                port:
                  number: 15672
          - path: /postgres(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: postgres-postgresql
                port:
                  number: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: rabbit-rabbitmq-foward
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: rabbit
    app.kubernetes.io/name: rabbitmq
  ports:
    - port: 5672
      targetPort: 5672
      name: amqp
    - port: 15672
      targetPort: 15672
      nodePort: 31672
      name: http                 